#CI for Ad Service

name: Ad_Service

run-name: ${ { github.workflow } }

on:
  push:
    branches:
      - main

jobs:
  build:          
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-java@main
        with:
          java-version: '21.0'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@main
                      
      - name: Build
        run: |
          java -version
          javac -version
          echo $JAVA_HOME
          cd src/ad          
          gradle -v
          gradle wrapper --gradle-version=8.12.1
          sudo chmod +x ./gradlew
          sudo ./gradlew clean build --no-daemon --warning-mode all -Dorg.gradle.java.home=/usr/lib/jvm/java-21-openjdk-amd64  --stacktrace
          sudo ./gradlew downloadRepos
          sudo cp -r ./pb ./proto
          sudo chmod +x ./gradlew
          sudo ./gradlew installDist -PprotoSourceDir=./proto
  docker:
    runs-on: ubuntu-latest

    needs: build

    steps:
      - name: checkout code
        uses: actions/checkout@main

      - name: Install Docker
        uses: docker/setup-buildx-action@main
      
      - name: Login to Docker
        uses: docker/login-action@main
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Docker Push
        uses: docker/build-push-action@main
        with:
          context: src/ad
          file: src/ad/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/ad:${{github.run_id}}



       

    
              

        

                            

        
