name: Ad_Service

run-name: ${ { github.workflow } }

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    build:
        name: Ad_Service_CI
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-java@main
              with:
                java-version: '17'
                distribution: 'temurin'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@main
            - name: Build with Gradle
              run: ./gradlew build

    docker:
        name: Ad_Service_Docker
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@main
            - uses: actions/setup-java@main
              with:
                java-version: '17'
                distribution: 'temurin'

            - name: Setup Gradle
              uses: gradle/actions/setup-gradle@main
            - name: Build Docker Image
              run: ./gradlew docker
                env:
                    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
                    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            - name: Push Docker Image
              run: ./gradlew dockerPush
              

        

                            

        
